language: go
go:
  - tip
services:
  - mongodb
go_import_path: github.com/iliyanmotovski/bankv1
install:
  - go get github.com/gorilla/context
  - go get github.com/golang/mock/gomock
  - go get github.com/justinas/alice
  - go get gopkg.in/mgo.v2
  - go get golang.org/x/crypto/bcrypt
  - go get gopkg.in/mgo.v2/bson
  - go get github.com/gorilla/mux
before_script:
  - sleep 3
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
script:
  - go test -v ./...